### ISSUE TITLE
Chart is v1.6.3 but deployment image is v1.7.4

### ISSUE THREAD

**Issue by juiposa** [influxdata/kube-influxdb#9]
The `influxdb` `Chart.yaml` say the Chart is for Influx v1.6.3
```
name: influxdb
version: 1.6.3
```
but the `values.yaml` would have the deployment pull an image for v1.7.4
```
image:
  repo: "influxdb"
  tag: "1.7.4-alpine"
  pullPolicy: IfNotPresent
```
